# Generated by Django 4.1.3 on 2025-04-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(default='CEE3A53FBA', max_length=10, unique=True),
        ),
    ]
