# Generated by Django 4.1.3 on 2025-04-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_question_test_alter_test_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(default='57E52A1E43', max_length=10, unique=True),
        ),
    ]
