# Generated by Django 4.1.3 on 2025-04-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_is_multiple_choice_alter_test_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(default='B8D95B5C72', max_length=10, unique=True),
        ),
    ]
