# Generated by Django 4.1.3 on 2025-04-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_test_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.question'),
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(default='E7D246FC71', max_length=10, unique=True),
        ),
    ]
