# Generated by Django 4.1.3 on 2025-04-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_option_question_alter_test_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(default='AF5BE4D644', max_length=10, unique=True),
        ),
    ]
