# Generated by Django 4.1.3 on 2025-04-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_test_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(default='B800B306BE', max_length=10, unique=True),
        ),
    ]
