# Generated by Django 4.1.3 on 2025-04-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question_correct_text_answer_alter_test_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(default='6C20712B4A', max_length=10, unique=True),
        ),
    ]
