# Generated by Django 4.1.3 on 2025-04-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_test_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
