# Generated by Django 4.1.3 on 2025-06-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_personalized',
            field=models.BooleanField(default=False),
        ),
    ]
