# Generated by Django 4.1.3 on 2025-06-02 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_test_is_personalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Мои настройки', max_length=255)),
                ('grading_type', models.CharField(choices=[('differentiated', 'Дифференцированное'), ('non_differentiated', 'Недифференцированное')], default='non_differentiated', max_length=20)),
                ('threshold_2', models.IntegerField(blank=True, default=40, null=True)),
                ('threshold_3', models.IntegerField(blank=True, default=60, null=True)),
                ('threshold_4', models.IntegerField(blank=True, default=80, null=True)),
                ('threshold_5', models.IntegerField(blank=True, default=90, null=True)),
                ('pass_threshold', models.IntegerField(blank=True, default=60, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='grading_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gradingscheme'),
        ),
    ]
